#include <iostream>
#include <fstream>
#include "ast.h"
#include "globals.h"
#include "helper.h"

// Declare functions generated by Flex and Bison
extern int yyparse();
extern FILE *yyin;

extern int yydebug;

// The parsed workout object
extern Workout *parsedWorkout;

int main(int argc, char **argv) {
    yydebug = 0;
    // Check if a file is provided as an argument
    if (argc > 1) {
        // Open the file for reading
        args = argv;
        FILE *file = fopen(argv[1], "r");
        if (!file) {
            std::cerr << "Could not open file: " << argv[1] << std::endl;
            return 1;
        }
        // Set the input stream for the lexer
        yyin = file;
    } else {
        std::cerr << "Usage: " << argv[0] << " <input file>" << std::endl;
        return 1;
    }

    initializeMaps();
    // Parse the input
    if (yyparse() == 0) {
        // If parsing succeeds, print the parsed workout details
        if (parsedWorkout) {
            parsedWorkout->printWorkout();

            for(const auto &pair : aliasToNameMap){
                std::cout << "Alias " << pair.first << " ,Actual name " << pair.second << std::endl;
            }
            std::cout << std::endl;
            for(const auto &pair : nameToTypeMap){
                std::cout << "Name " << pair.first << " ,Type " << pair.second << std::endl;
            }
        } else {
            std::cerr << "No workout data was parsed." << std::endl;
        }
    } else {
        std::cerr << "Parsing failed!" << std::endl;
    }

    // Clean up
    if (parsedWorkout) {
        delete parsedWorkout;
    }

    // Close the input file if opened
    if (yyin) {
        fclose(yyin);
    }

    return 0;
}